version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: lab1_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lab1sskbd
      MYSQL_USER: user3
      MYSQL_PASSWORD: 12345
    ports:
      - "3306:3306"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql

  php:
    build: ./web
    container_name: lab1_php
    restart: always
    depends_on:
      - mysql
    ports:
      - "8080:80"
    volumes:
      - ./web:/var/www/html

volumes:
  mysql_data:
